apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-auth-server
  annotations:
    kubernetes.io/ingress.class: "kong"
    # konghq.com/plugins: my-custom-plugin
spec:
  rules:
  - http:
      paths:
      - path: /auth/
        backend:
          serviceName: kong-auth-server
          servicePort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kong-auth-server
    labels:
        name: kong-auth-server
spec:
    replicas: 1
    selector:
        matchLabels:
            name: kong-auth-server
    template:
        metadata:
            labels:
                name: kong-auth-server
        spec:
            containers:
                - name: kong-auth-server
                  image: kong-auth-server
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
    name: kong-auth-server
spec:
    ports:
        - name: http
          port: 8001
          protocol: TCP
          targetPort: 8088
    selector:
        name: kong-auth-server
---
